window.esdocSearchIndex = [
  [
    "autonym/lib/autonymerror~autonymerror",
    "class/src/AutonymError.js~AutonymError.html",
    "<span>AutonymError</span> <span class=\"search-result-import-path\">autonym/lib/AutonymError</span>",
    "class"
  ],
  [
    "autonym/lib/model~model",
    "class/src/Model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">autonym/lib/Model</span>",
    "class"
  ],
  [
    "autonym/lib/req~req",
    "class/src/Req.js~Req.html",
    "<span>Req</span> <span class=\"search-result-import-path\">autonym/lib/Req</span>",
    "class"
  ],
  [
    "autonym/lib/res~res",
    "class/src/Res.js~Res.html",
    "<span>Res</span> <span class=\"search-result-import-path\">autonym/lib/Res</span>",
    "class"
  ],
  [
    "autonym/lib/createinmemorystore~createinmemorystore",
    "function/index.html#static-function-createInMemoryStore",
    "<span>createInMemoryStore</span> <span class=\"search-result-import-path\">autonym/lib/createInMemoryStore</span>",
    "function"
  ],
  [
    "autonym/lib/createmodelmiddleware~createmodelmiddleware",
    "function/index.html#static-function-createModelMiddleware",
    "<span>createModelMiddleware</span> <span class=\"search-result-import-path\">autonym/lib/createModelMiddleware</span>",
    "function"
  ],
  [
    "autonym/lib/createrespondermiddleware~createrespondermiddleware",
    "function/index.html#static-function-createResponderMiddleware",
    "<span>createResponderMiddleware</span> <span class=\"search-result-import-path\">autonym/lib/createResponderMiddleware</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/.external-nodejs.js~http~clientrequest",
    "https://nodejs.org/dist/latest/docs/api/http.html#http_class_http_clientrequest",
    "src/.external-nodejs.js~http~ClientRequest",
    "external"
  ],
  [
    "src/autonymerror.js",
    "file/src/AutonymError.js.html",
    "src/AutonymError.js",
    "file"
  ],
  [
    "src/autonymerror.js~autonymerror#constructor",
    "class/src/AutonymError.js~AutonymError.html#instance-constructor-constructor",
    "src/AutonymError.js~AutonymError#constructor",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#getcode",
    "class/src/AutonymError.js~AutonymError.html#instance-method-getCode",
    "src/AutonymError.js~AutonymError#getCode",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#getdata",
    "class/src/AutonymError.js~AutonymError.html#instance-method-getData",
    "src/AutonymError.js~AutonymError#getData",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#getmessage",
    "class/src/AutonymError.js~AutonymError.html#instance-method-getMessage",
    "src/AutonymError.js~AutonymError#getMessage",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#getpayload",
    "class/src/AutonymError.js~AutonymError.html#instance-method-getPayload",
    "src/AutonymError.js~AutonymError#getPayload",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#getstatus",
    "class/src/AutonymError.js~AutonymError.html#instance-method-getStatus",
    "src/AutonymError.js~AutonymError#getStatus",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#isclienterror",
    "class/src/AutonymError.js~AutonymError.html#instance-method-isClientError",
    "src/AutonymError.js~AutonymError#isClientError",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror#toclienterror",
    "class/src/AutonymError.js~AutonymError.html#instance-method-toClientError",
    "src/AutonymError.js~AutonymError#toClientError",
    "method"
  ],
  [
    "src/autonymerror.js~autonymerror.bad_request",
    "class/src/AutonymError.js~AutonymError.html#static-member-BAD_REQUEST",
    "src/AutonymError.js~AutonymError.BAD_REQUEST",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.client_errors",
    "class/src/AutonymError.js~AutonymError.html#static-member-CLIENT_ERRORS",
    "src/AutonymError.js~AutonymError.CLIENT_ERRORS",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.forbidden",
    "class/src/AutonymError.js~AutonymError.html#static-member-FORBIDDEN",
    "src/AutonymError.js~AutonymError.FORBIDDEN",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.internal_server_error",
    "class/src/AutonymError.js~AutonymError.html#static-member-INTERNAL_SERVER_ERROR",
    "src/AutonymError.js~AutonymError.INTERNAL_SERVER_ERROR",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.method_not_allowed",
    "class/src/AutonymError.js~AutonymError.html#static-member-METHOD_NOT_ALLOWED",
    "src/AutonymError.js~AutonymError.METHOD_NOT_ALLOWED",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.not_found",
    "class/src/AutonymError.js~AutonymError.html#static-member-NOT_FOUND",
    "src/AutonymError.js~AutonymError.NOT_FOUND",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.unauthorized",
    "class/src/AutonymError.js~AutonymError.html#static-member-UNAUTHORIZED",
    "src/AutonymError.js~AutonymError.UNAUTHORIZED",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.unprocessable_entity",
    "class/src/AutonymError.js~AutonymError.html#static-member-UNPROCESSABLE_ENTITY",
    "src/AutonymError.js~AutonymError.UNPROCESSABLE_ENTITY",
    "member"
  ],
  [
    "src/autonymerror.js~autonymerror.fromerror",
    "class/src/AutonymError.js~AutonymError.html#static-method-fromError",
    "src/AutonymError.js~AutonymError.fromError",
    "method"
  ],
  [
    "src/model.js",
    "file/src/Model.js.html",
    "src/Model.js",
    "file"
  ],
  [
    "src/model.js~model#constructor",
    "class/src/Model.js~Model.html#instance-constructor-constructor",
    "src/Model.js~Model#constructor",
    "method"
  ],
  [
    "src/model.js~model#create",
    "class/src/Model.js~Model.html#instance-method-create",
    "src/Model.js~Model#create",
    "method"
  ],
  [
    "src/model.js~model#find",
    "class/src/Model.js~Model.html#instance-method-find",
    "src/Model.js~Model#find",
    "method"
  ],
  [
    "src/model.js~model#findone",
    "class/src/Model.js~Model.html#instance-method-findOne",
    "src/Model.js~Model#findOne",
    "method"
  ],
  [
    "src/model.js~model#findoneanddelete",
    "class/src/Model.js~Model.html#instance-method-findOneAndDelete",
    "src/Model.js~Model#findOneAndDelete",
    "method"
  ],
  [
    "src/model.js~model#findoneandupdate",
    "class/src/Model.js~Model.html#instance-method-findOneAndUpdate",
    "src/Model.js~Model#findOneAndUpdate",
    "method"
  ],
  [
    "src/model.js~model#getconfig",
    "class/src/Model.js~Model.html#instance-method-getConfig",
    "src/Model.js~Model#getConfig",
    "method"
  ],
  [
    "src/model.js~model#getinitialmeta",
    "class/src/Model.js~Model.html#instance-method-getInitialMeta",
    "src/Model.js~Model#getInitialMeta",
    "method"
  ],
  [
    "src/model.js~model#getname",
    "class/src/Model.js~Model.html#instance-method-getName",
    "src/Model.js~Model#getName",
    "method"
  ],
  [
    "src/model.js~model#getpolicies",
    "class/src/Model.js~Model.html#instance-method-getPolicies",
    "src/Model.js~Model#getPolicies",
    "method"
  ],
  [
    "src/model.js~model#getroute",
    "class/src/Model.js~Model.html#instance-method-getRoute",
    "src/Model.js~Model#getRoute",
    "method"
  ],
  [
    "src/model.js~model#init",
    "class/src/Model.js~Model.html#instance-method-init",
    "src/Model.js~Model#init",
    "method"
  ],
  [
    "src/model.js~model#serialize",
    "class/src/Model.js~Model.html#instance-method-serialize",
    "src/Model.js~Model#serialize",
    "method"
  ],
  [
    "src/model.js~model#unserialize",
    "class/src/Model.js~Model.html#instance-method-unserialize",
    "src/Model.js~Model#unserialize",
    "method"
  ],
  [
    "src/model.js~model#validateagainstschema",
    "class/src/Model.js~Model.html#instance-method-validateAgainstSchema",
    "src/Model.js~Model#validateAgainstSchema",
    "method"
  ],
  [
    "src/model.js~model#withhooks",
    "class/src/Model.js~Model.html#instance-method-withHooks",
    "src/Model.js~Model#withHooks",
    "method"
  ],
  [
    "src/req.js",
    "file/src/Req.js.html",
    "src/Req.js",
    "file"
  ],
  [
    "src/req.js~req#constructor",
    "class/src/Req.js~Req.html#instance-constructor-constructor",
    "src/Req.js~Req#constructor",
    "method"
  ],
  [
    "src/req.js~req#getcompletedata",
    "class/src/Req.js~Req.html#instance-method-getCompleteData",
    "src/Req.js~Req#getCompleteData",
    "method"
  ],
  [
    "src/req.js~req#getdata",
    "class/src/Req.js~Req.html#instance-method-getData",
    "src/Req.js~Req#getData",
    "method"
  ],
  [
    "src/req.js~req#getheader",
    "class/src/Req.js~Req.html#instance-method-getHeader",
    "src/Req.js~Req#getHeader",
    "method"
  ],
  [
    "src/req.js~req#getid",
    "class/src/Req.js~Req.html#instance-method-getId",
    "src/Req.js~Req#getId",
    "method"
  ],
  [
    "src/req.js~req#getmodel",
    "class/src/Req.js~Req.html#instance-method-getModel",
    "src/Req.js~Req#getModel",
    "method"
  ],
  [
    "src/req.js~req#getoriginaldata",
    "class/src/Req.js~Req.html#instance-method-getOriginalData",
    "src/Req.js~Req#getOriginalData",
    "method"
  ],
  [
    "src/req.js~req#getquery",
    "class/src/Req.js~Req.html#instance-method-getQuery",
    "src/Req.js~Req#getQuery",
    "method"
  ],
  [
    "src/req.js~req#getraw",
    "class/src/Req.js~Req.html#instance-method-getRaw",
    "src/Req.js~Req#getRaw",
    "method"
  ],
  [
    "src/req.js~req#getrequestdata",
    "class/src/Req.js~Req.html#instance-method-getRequestData",
    "src/Req.js~Req#getRequestData",
    "method"
  ],
  [
    "src/req.js~req#hasbody",
    "class/src/Req.js~Req.html#instance-method-hasBody",
    "src/Req.js~Req#hasBody",
    "method"
  ],
  [
    "src/req.js~req#hasid",
    "class/src/Req.js~Req.html#instance-method-hasId",
    "src/Req.js~Req#hasId",
    "method"
  ],
  [
    "src/req.js~req#iscreating",
    "class/src/Req.js~Req.html#instance-method-isCreating",
    "src/Req.js~Req#isCreating",
    "method"
  ],
  [
    "src/req.js~req#isfinding",
    "class/src/Req.js~Req.html#instance-method-isFinding",
    "src/Req.js~Req#isFinding",
    "method"
  ],
  [
    "src/req.js~req#isfindingone",
    "class/src/Req.js~Req.html#instance-method-isFindingOne",
    "src/Req.js~Req#isFindingOne",
    "method"
  ],
  [
    "src/req.js~req#isfindingoneanddeleting",
    "class/src/Req.js~Req.html#instance-method-isFindingOneAndDeleting",
    "src/Req.js~Req#isFindingOneAndDeleting",
    "method"
  ],
  [
    "src/req.js~req#isfindingoneandupdating",
    "class/src/Req.js~Req.html#instance-method-isFindingOneAndUpdating",
    "src/Req.js~Req#isFindingOneAndUpdating",
    "method"
  ],
  [
    "src/req.js~req#isgetting",
    "class/src/Req.js~Req.html#instance-method-isGetting",
    "src/Req.js~Req#isGetting",
    "method"
  ],
  [
    "src/req.js~req#isreading",
    "class/src/Req.js~Req.html#instance-method-isReading",
    "src/Req.js~Req#isReading",
    "method"
  ],
  [
    "src/req.js~req#isvalidated",
    "class/src/Req.js~Req.html#instance-method-isValidated",
    "src/Req.js~Req#isValidated",
    "method"
  ],
  [
    "src/req.js~req#iswriting",
    "class/src/Req.js~Req.html#instance-method-isWriting",
    "src/Req.js~Req#isWriting",
    "method"
  ],
  [
    "src/req.js~req#setdata",
    "class/src/Req.js~Req.html#instance-method-setData",
    "src/Req.js~Req#setData",
    "method"
  ],
  [
    "src/res.js",
    "file/src/Res.js.html",
    "src/Res.js",
    "file"
  ],
  [
    "src/res.js~res#constructor",
    "class/src/Res.js~Res.html#instance-constructor-constructor",
    "src/Res.js~Res#constructor",
    "method"
  ],
  [
    "src/res.js~res#getdata",
    "class/src/Res.js~Res.html#instance-method-getData",
    "src/Res.js~Res#getData",
    "method"
  ],
  [
    "src/res.js~res#getheader",
    "class/src/Res.js~Res.html#instance-method-getHeader",
    "src/Res.js~Res#getHeader",
    "method"
  ],
  [
    "src/res.js~res#getmodel",
    "class/src/Res.js~Res.html#instance-method-getModel",
    "src/Res.js~Res#getModel",
    "method"
  ],
  [
    "src/res.js~res#getraw",
    "class/src/Res.js~Res.html#instance-method-getRaw",
    "src/Res.js~Res#getRaw",
    "method"
  ],
  [
    "src/res.js~res#getstatus",
    "class/src/Res.js~Res.html#instance-method-getStatus",
    "src/Res.js~Res#getStatus",
    "method"
  ],
  [
    "src/res.js~res#ispopulated",
    "class/src/Res.js~Res.html#instance-method-isPopulated",
    "src/Res.js~Res#isPopulated",
    "method"
  ],
  [
    "src/res.js~res#issent",
    "class/src/Res.js~Res.html#instance-method-isSent",
    "src/Res.js~Res#isSent",
    "method"
  ],
  [
    "src/res.js~res#setdata",
    "class/src/Res.js~Res.html#instance-method-setData",
    "src/Res.js~Res#setData",
    "method"
  ],
  [
    "src/res.js~res#setheader",
    "class/src/Res.js~Res.html#instance-method-setHeader",
    "src/Res.js~Res#setHeader",
    "method"
  ],
  [
    "src/res.js~res#setstatus",
    "class/src/Res.js~Res.html#instance-method-setStatus",
    "src/Res.js~Res#setStatus",
    "method"
  ],
  [
    "src/res.js~res.created",
    "class/src/Res.js~Res.html#static-member-CREATED",
    "src/Res.js~Res.CREATED",
    "member"
  ],
  [
    "src/res.js~res.ok",
    "class/src/Res.js~Res.html#static-member-OK",
    "src/Res.js~Res.OK",
    "member"
  ],
  [
    "src/_typedefs.js",
    "file/src/_typeDefs.js.html",
    "src/_typeDefs.js",
    "file"
  ],
  [
    "src/_typedefs.js~ajvoptions",
    "typedef/index.html#static-typedef-AjvOptions",
    "src/_typeDefs.js~AjvOptions",
    "typedef"
  ],
  [
    "src/_typedefs.js~andexpression",
    "typedef/index.html#static-typedef-AndExpression",
    "src/_typeDefs.js~AndExpression",
    "typedef"
  ],
  [
    "src/_typedefs.js~meta",
    "typedef/index.html#static-typedef-Meta",
    "src/_typeDefs.js~Meta",
    "typedef"
  ],
  [
    "src/_typedefs.js~modelpolicies",
    "typedef/index.html#static-typedef-ModelPolicies",
    "src/_typeDefs.js~ModelPolicies",
    "typedef"
  ],
  [
    "src/_typedefs.js~notexpression",
    "typedef/index.html#static-typedef-NotExpression",
    "src/_typeDefs.js~NotExpression",
    "typedef"
  ],
  [
    "src/_typedefs.js~operand",
    "typedef/index.html#static-typedef-Operand",
    "src/_typeDefs.js~Operand",
    "typedef"
  ],
  [
    "src/_typedefs.js~orexpression",
    "typedef/index.html#static-typedef-OrExpression",
    "src/_typeDefs.js~OrExpression",
    "typedef"
  ],
  [
    "src/_typedefs.js~policy",
    "typedef/index.html#static-typedef-Policy",
    "src/_typeDefs.js~Policy",
    "typedef"
  ],
  [
    "src/_typedefs.js~record",
    "typedef/index.html#static-typedef-Record",
    "src/_typeDefs.js~Record",
    "typedef"
  ],
  [
    "src/_typedefs.js~schema",
    "typedef/index.html#static-typedef-Schema",
    "src/_typeDefs.js~Schema",
    "typedef"
  ],
  [
    "src/_typedefs.js~serializedrecord",
    "typedef/index.html#static-typedef-SerializedRecord",
    "src/_typeDefs.js~SerializedRecord",
    "typedef"
  ],
  [
    "src/_typedefs.js~store",
    "typedef/index.html#static-typedef-Store",
    "src/_typeDefs.js~Store",
    "typedef"
  ],
  [
    "src/createinmemorystore.js",
    "file/src/createInMemoryStore.js.html",
    "src/createInMemoryStore.js",
    "file"
  ],
  [
    "src/createmodelmiddleware.js",
    "file/src/createModelMiddleware.js.html",
    "src/createModelMiddleware.js",
    "file"
  ],
  [
    "src/createrespondermiddleware.js",
    "file/src/createResponderMiddleware.js.html",
    "src/createResponderMiddleware.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/middleware/createerrormiddleware.js",
    "file/src/middleware/createErrorMiddleware.js.html",
    "src/middleware/createErrorMiddleware.js",
    "file"
  ],
  [
    "src/middleware/createstoremiddleware.js",
    "file/src/middleware/createStoreMiddleware.js.html",
    "src/middleware/createStoreMiddleware.js",
    "file"
  ],
  [
    "src/middleware/index.js",
    "file/src/middleware/index.js.html",
    "src/middleware/index.js",
    "file"
  ],
  [
    "src/utils/index.js",
    "file/src/utils/index.js.html",
    "src/utils/index.js",
    "file"
  ]
]