site_dir: ../docs
site_name: Autonym
site_url: https://autonym.io
repo_url: https://github.com/mmiller42/autonym
copyright: 'Autonym © <a href="https://mmiller.me/">Matt Miller</a> and licensed under the
  <a href="https://github.com/mmiller42/autonym/blob/master/LICENSE">MIT license</a>'
theme: cinder
extra_css:
- "css/custom.css"
pages:
- Intro: index.md
- Getting Started: getting-started.md
- req & res: req-and-res.md
- Autonym: autonym.md
- AutonymResponder: autonym-responder.md
- Model: model.md
- Client Errors: client-errors.md
- Creating a Store: creating-a-store.md
